import React, { useState, useEffect } from 'react';
import RouteRow from './components/RouteRow';
import RouteSkeleton from './components/RouteSkeleton';
import { fetchTopRoutes } from './data/telemetryApi';

// Accepts a callback prop to interact with the main search engine when a route is clicked
const PopularRoutes = ({ onSelectRoute }) => {
  const [routes, setRoutes] = useState([]);
    const [isLoading, setIsLoading] = useState(true);

      useEffect(() => {
          let mounted = true;
              
                  const loadTelemetry = async () => {
                        setIsLoading(true);
                              const data = await fetchTopRoutes(10); // Fetch top 10 for scrollability
                                    if (mounted) {
                                            setRoutes(data);
                                                    setIsLoading(false);
                                                          }
                                                              };

                                                                  loadTelemetry();

                                                                      return () => {
                                                                            mounted = false;
                                                                                };
                                                                                  }, []);

                                                                                    const handleRouteSelection = (origin, destination) => {
                                                                                        // Passes the selected telemetry data back up to populate the main search bar
                                                                                            if (onSelectRoute) {
                                                                                                  onSelectRoute(origin, destination);
                                                                                                      }
                                                                                                        };

                                                                                                          return (
                                                                                                              <div className="ayabus-card" style={{ display: 'flex', flexDirection: 'column', height: '100%', maxHeight: '350px', padding: '0', overflow: 'hidden' }}>
                                                                                                                    
                                                                                                                          {/* Sticky Header */}
                                                                                                                                <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border-strong)', backgroundColor: 'var(--bg-surface)', zIndex: 2 }}>
                                                                                                                                        <h3 style={{ fontSize: '16px', fontWeight: '800', color: 'var(--text-main)', margin: 0, textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                                                                                                                                                  Trending Routes
                                                                                                                                                          </h3>
                                                                                                                                                                  <p style={{ fontSize: '12px', color: 'var(--text-muted)', margin: '4px 0 0 0' }}>
                                                                                                                                                                            Based on live network searches
                                                                                                                                                                                    </p>
                                                                                                                                                                                          </div>

                                                                                                                                                                                                {/* Scrollable List Container */}
                                                                                                                                                                                                      <div className="ayabus-hide-scrollbar" style={{ flex: 1, overflowY: 'auto', padding: '12px 20px' }}>
                                                                                                                                                                                                              {isLoading ? (
                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                    <RouteSkeleton />
                                                                                                                                                                                                                                                <RouteSkeleton />
                                                                                                                                                                                                                                                            <RouteSkeleton />
                                                                                                                                                                                                                                                                        <RouteSkeleton />
                                                                                                                                                                                                                                                                                    <RouteSkeleton />
                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                      ) : routes.length > 0 ? (
                                                                                                                                                                                                                                                                                                                routes.map((route) => (
                                                                                                                                                                                                                                                                                                                            <RouteRow 
                                                                                                                                                                                                                                                                                                                                          key={route.id} 
                                                                                                                                                                                                                                                                                                                                                        route={route} 
                                                                                                                                                                                                                                                                                                                                                                      onRouteClick={handleRouteSelection} 
                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                            ))
                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ textAlign: 'center', padding: '24px 0', color: 'var(--text-muted)', fontSize: '13px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                          No trending data currently available.
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Fade out effect at the bottom of the scroll to indicate more content */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      position: 'absolute',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              bottom: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      left: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              right: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      height: '30px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: 'linear-gradient(to bottom, transparent, var(--bg-surface))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pointerEvents: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderBottomLeftRadius: 'var(--radius-lg)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderBottomRightRadius: 'var(--radius-lg)'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}></div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default PopularRoutes;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  