import React, { useState, useEffect } from 'react';
import ReviewInputForm from './components/ReviewInputForm';
import ReviewTicker from './components/ReviewTicker';
import { fetchRecentReviews, submitUserReview } from './data/reviewsApi';

const ReviewsModule = () => {
  const [reviews, setReviews] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
      const [isSubmitting, setIsSubmitting] = useState(false);
        const [feedback, setFeedback] = useState(null);

          // Load initial reviews
            useEffect(() => {
                let mounted = true;
                    const loadReviews = async () => {
                          const data = await fetchRecentReviews();
                                if (mounted) {
                                        setReviews(data);
                                                setIsLoading(false);
                                                      }
                                                          };
                                                              loadReviews();
                                                                  return () => { mounted = false; };
                                                                    }, []);

                                                                      const handleReviewSubmit = async (authorName, content) => {
                                                                          setIsSubmitting(true);
                                                                              setFeedback(null);
                                                                                  try {
                                                                                        const newReview = await submitUserReview(authorName, content);
                                                                                              // Optimistically insert the new review at the top of the array
                                                                                                    setReviews(prev => [newReview, ...prev]);
                                                                                                          setFeedback({ type: 'success', message: 'Review published successfully!' });
                                                                                                                
                                                                                                                      // Clear success message after 4 seconds
                                                                                                                            setTimeout(() => setFeedback(null), 4000);
                                                                                                                                } catch (error) {
                                                                                                                                      setFeedback({ type: 'error', message: 'Failed to send review. Try again later.' });
                                                                                                                                          } finally {
                                                                                                                                                setIsSubmitting(false);
                                                                                                                                                    }
                                                                                                                                                      };

                                                                                                                                                        return (
                                                                                                                                                            <div className="ayabus-card" style={{ padding: '0', overflow: 'hidden', backgroundColor: 'var(--bg-surface)' }}>
                                                                                                                                                                  <div className="reviews-matrix">
                                                                                                                                                                          
                                                                                                                                                                                  {/* LEFT COLUMN: Input & Context */}
                                                                                                                                                                                          <div className="reviews-input-panel" style={{ padding: '40px', borderRight: '1px solid var(--border-subtle)', display: 'flex', flexDirection: 'column', gap: '24px' }}>
                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                <h2 style={{ fontSize: '28px', fontWeight: '900', color: 'var(--text-main)', margin: '0 0 8px 0', letterSpacing: '-0.5px' }}>
                                                                                                                                                                                                                              Traveler Voices
                                                                                                                                                                                                                                          </h2>
                                                                                                                                                                                                                                                      <p style={{ fontSize: '14px', color: 'var(--text-muted)', margin: 0, lineHeight: '1.6' }}>
                                                                                                                                                                                                                                                                    We build this network for you. Read what others are saying and share your own journey below.
                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                    <ReviewInputForm onSubmit={handleReviewSubmit} isSubmitting={isSubmitting} />

                                                                                                                                                                                                                                                                                                              {feedback && (
                                                                                                                                                                                                                                                                                                                          <div style={{ 
                                                                                                                                                                                                                                                                                                                                        padding: '12px', borderRadius: 'var(--radius-sm)', fontSize: '13px', fontWeight: '600',
                                                                                                                                                                                                                                                                                                                                                      backgroundColor: feedback.type === 'success' ? 'var(--status-success)' : 'var(--status-error)',
                                                                                                                                                                                                                                                                                                                                                                    color: '#FFFFFF'
                                                                                                                                                                                                                                                                                                                                                                                }}>
                                                                                                                                                                                                                                                                                                                                                                                              {feedback.message}
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ marginTop: 'auto', paddingTop: '16px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* The live wire routing to a dedicated full-page reviews view if built later */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="ayabus-btn ayabus-btn-ghost" style={{ width: '100%', fontSize: '12px', justifyContent: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    See All Reviews ➔
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* RIGHT COLUMN: The Scrolling Ticker */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="reviews-ticker-panel" style={{ padding: '40px', backgroundColor: 'var(--bg-input)', display: 'flex', flexDirection: 'column' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <ReviewTicker reviews={reviews} isLoading={isLoading} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {/* --- RESPONSIVE CSS INJECTION --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <style>{`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               .reviews-matrix {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   align-items: stretch;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             .reviews-input-panel {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       flex: 1 1 50%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       .reviews-ticker-panel {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 flex: 1 1 50%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 /* Mobile Breakpoint Adjustment */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         @media (max-width: 992px) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   .reviews-matrix {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               flex-direction: column;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   .reviews-input-panel {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               padding: 32px 24px !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           border-right: none !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       border-bottom: 1px solid var(--border-subtle);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           .reviews-ticker-panel {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       padding: 24px !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   height: 400px; /* Give a fixed height on mobile so it doesn't take over the screen */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           `}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 export default ReviewsModule;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 