import React, { useState } from 'react';
import NewsletterForm from './components/NewsletterForm';
import SubscribeFeedback from './components/SubscribeFeedback';
import { subscribeUser } from './data/subscribeApi';
import { isValidEmail } from './utils/validators';

const NewsletterModule = () => {
  const [formData, setFormData] = useState({ email: '', city: '' });
    const [status, setStatus] = useState({ type: 'idle', message: '' }); // 'idle' | 'loading' | 'success' | 'error'

      const handleSubmit = async (e) => {
          e.preventDefault();
              setStatus({ type: 'loading', message: '' });

                  if (!isValidEmail(formData.email)) {
                        setStatus({ type: 'error', message: 'Please enter a valid email address.' });
                              return;
                                  }

                                      if (!formData.city.trim()) {
                                            setStatus({ type: 'error', message: 'Please enter your city for localized offers.' });
                                                  return;
                                                      }

                                                          try {
                                                                await subscribeUser(formData.email, formData.city);
                                                                      setStatus({ type: 'success', message: `Welcome aboard! We'll send the best deals for ${formData.city} right to your inbox.` });
                                                                            setFormData({ email: '', city: '' }); // Clear form on success
                                                                                } catch (error) {
                                                                                      setStatus({ type: 'error', message: error.message });
                                                                                          }
                                                                                            };

                                                                                              return (
                                                                                                  <div 
                                                                                                        className="ayabus-card" 
                                                                                                              style={{ 
                                                                                                                      padding: '32px', 
                                                                                                                              position: 'relative',
                                                                                                                                      overflow: 'hidden',
                                                                                                                                              display: 'flex',
                                                                                                                                                      flexDirection: 'column',
                                                                                                                                                              gap: '24px',
                                                                                                                                                                      backgroundColor: 'var(--brand-subtle)', // Subtle brand tint for emphasis on homepage
                                                                                                                                                                              border: '1px solid var(--brand-primary)'
                                                                                                                                                                                    }}
                                                                                                                                                                                        >
                                                                                                                                                                                              {/* Decorative Background Element for World-Class Feel */}
                                                                                                                                                                                                    <div style={{
                                                                                                                                                                                                            position: 'absolute',
                                                                                                                                                                                                                    top: '-50%',
                                                                                                                                                                                                                            right: '-10%',
                                                                                                                                                                                                                                    width: '300px',
                                                                                                                                                                                                                                            height: '300px',
                                                                                                                                                                                                                                                    background: 'var(--brand-primary)',
                                                                                                                                                                                                                                                            opacity: '0.05',
                                                                                                                                                                                                                                                                    borderRadius: '50%',
                                                                                                                                                                                                                                                                            pointerEvents: 'none'
                                                                                                                                                                                                                                                                                  }} />

                                                                                                                                                                                                                                                                                        {/* Header Section */}
                                                                                                                                                                                                                                                                                              <div style={{ zIndex: 1 }}>
                                                                                                                                                                                                                                                                                                      <h2 style={{ fontSize: '24px', fontWeight: '900', color: 'var(--text-main)', marginBottom: '8px', letterSpacing: '-0.5px' }}>
                                                                                                                                                                                                                                                                                                                Unlock Exclusive Local Offers
                                                                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                                                                <p style={{ fontSize: '15px', color: 'var(--text-muted)', margin: 0, lineHeight: '1.5' }}>
                                                                                                                                                                                                                                                                                                                                          Join the network. Get the latest routes, discounts, and travel updates specific to your city delivered straight to your inbox.
                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                              {/* Main Interaction Area */}
                                                                                                                                                                                                                                                                                                                                                                    <div style={{ zIndex: 1 }}>
                                                                                                                                                                                                                                                                                                                                                                            {status.type === 'success' ? (
                                                                                                                                                                                                                                                                                                                                                                                      <SubscribeFeedback type="success" message={status.message} />
                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                    <NewsletterForm 
                                                                                                                                                                                                                                                                                                                                                                                                                                  formData={formData} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                setFormData={setFormData} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              onSubmit={handleSubmit} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isLoading={status.type === 'loading'} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {status.type === 'error' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <SubscribeFeedback type="error" message={status.message} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Privacy Promise */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ zIndex: 1, fontSize: '12px', color: 'var(--text-muted)', marginTop: '-8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                We respect your privacy. No spam, ever. Unsubscribe at any time.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default NewsletterModule;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            