import React, { useState } from 'react';

const ReviewInputForm = ({ onSubmit, isSubmitting }) => {
  const [authorName, setAuthorName] = useState('');
    const [content, setContent] = useState('');
      const MAX_CHARS = 1000;

        const handleSubmit = (e) => {
            e.preventDefault();
                if (content.trim().length > 0) {
                      onSubmit(authorName, content);
                            setContent(''); // Clear on submit
                                  setAuthorName('');
                                      }
                                        };

                                          return (
                                              <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                                                    <div>
                                                            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-muted)', marginBottom: '8px', fontWeight: '600', textTransform: 'uppercase' }}>
                                                                      Your Name (Optional)
                                                                              </label>
                                                                                      <input 
                                                                                                type="text" 
                                                                                                          className="ayabus-input" 
                                                                                                                    placeholder="Anonymous"
                                                                                                                              value={authorName}
                                                                                                                                        onChange={(e) => setAuthorName(e.target.value)}
                                                                                                                                                  disabled={isSubmitting}
                                                                                                                                                          />
                                                                                                                                                                </div>

                                                                                                                                                                      <div>
                                                                                                                                                                              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                                                                                                                                                                                        <label style={{ fontSize: '12px', color: 'var(--text-muted)', fontWeight: '600', textTransform: 'uppercase' }}>
                                                                                                                                                                                                    Your Review
                                                                                                                                                                                                              </label>
                                                                                                                                                                                                                        <span style={{ fontSize: '12px', color: content.length > MAX_CHARS * 0.9 ? 'var(--status-error)' : 'var(--text-muted)' }}>
                                                                                                                                                                                                                                    {content.length} / {MAX_CHARS}
                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                              <textarea 
                                                                                                                                                                                                                                                                        className="ayabus-input" 
                                                                                                                                                                                                                                                                                  placeholder="Share your experience traveling with AyaBus..."
                                                                                                                                                                                                                                                                                            value={content}
                                                                                                                                                                                                                                                                                                      onChange={(e) => setContent(e.target.value.slice(0, MAX_CHARS))}
                                                                                                                                                                                                                                                                                                                disabled={isSubmitting}
                                                                                                                                                                                                                                                                                                                          style={{ height: '120px', resize: 'vertical', paddingTop: '12px' }}
                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                        <button 
                                                                                                                                                                                                                                                                                                                                                                type="submit" 
                                                                                                                                                                                                                                                                                                                                                                        className="ayabus-btn ayabus-btn-primary" 
                                                                                                                                                                                                                                                                                                                                                                                disabled={isSubmitting || content.trim().length === 0}
                                                                                                                                                                                                                                                                                                                                                                                        style={{ width: '100%', justifyContent: 'center' }}
                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                      {isSubmitting ? 'Sending...' : 'Send Review'}
                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                  export default ReviewInputForm;
                                                                                                                                                                                                                                                                                                                                                                                                                  