import React, { useState, useEffect } from 'react';
import RatingStats from './components/RatingStats';
import InteractiveStars from './components/InteractiveStars';
import SubmissionFeedback from './components/SubmissionFeedback';
import { fetchRatingStats, submitPlatformRating } from './data/ratingsApi';

const RatingsModule = () => {
  const [stats, setStats] = useState({ average: 0, total: 0 });
    const [userRating, setUserRating] = useState(0);
      const [isSubmitting, setIsSubmitting] = useState(false);
        const [hasSubmitted, setHasSubmitted] = useState(false);
          const [error, setError] = useState(null);

            useEffect(() => {
                let mounted = true;
                    const loadStats = async () => {
                          const data = await fetchRatingStats();
                                if (mounted) setStats(data);
                                    };
                                        loadStats();
                                            return () => { mounted = false; };
                                              }, []);

                                                const handleRatingSubmit = async () => {
                                                    if (userRating === 0) return;
                                                        setIsSubmitting(true);
                                                            setError(null);
                                                                try {
                                                                      await submitPlatformRating(userRating);
                                                                            setHasSubmitted(true);
                                                                                  // Optimistically update the stats on the screen
                                                                                        setStats(prev => ({
                                                                                                total: prev.total + 1,
                                                                                                        average: ((prev.average * prev.total) + userRating) / (prev.total + 1)
                                                                                                              }));
                                                                                                                  } catch (err) {
                                                                                                                        setError("Failed to submit rating. Please try again.");
                                                                                                                            } finally {
                                                                                                                                  setIsSubmitting(false);
                                                                                                                                      }
                                                                                                                                        };

                                                                                                                                          return (
                                                                                                                                              <div className="ayabus-card" style={{ padding: '0', overflow: 'hidden', backgroundColor: 'var(--bg-canvas)' }}>
                                                                                                                                                    <div className="ratings-matrix">
                                                                                                                                                            
                                                                                                                                                                    {/* LEFT PANEL: Global Statistics */}
                                                                                                                                                                            <div className="ratings-panel" style={{ 
                                                                                                                                                                                      backgroundColor: 'var(--bg-surface)', padding: '40px', 
                                                                                                                                                                                                display: 'flex', flexDirection: 'column', justifyContent: 'center', borderRight: '1px solid var(--border-subtle)' 
                                                                                                                                                                                                        }}>
                                                                                                                                                                                                                  <h3 style={{ fontSize: '14px', fontWeight: '800', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px', margin: '0 0 24px 0' }}>
                                                                                                                                                                                                                              Platform Excellence
                                                                                                                                                                                                                                        </h3>
                                                                                                                                                                                                                                                  <RatingStats average={stats.average} total={stats.total} />
                                                                                                                                                                                                                                                            <p style={{ marginTop: '24px', fontSize: '14px', color: 'var(--text-muted)', lineHeight: '1.6' }}>
                                                                                                                                                                                                                                                                        AyaBus is committed to world-class service. Our ratings are universally verified and syndicated across our partner networks.
                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                  {/* RIGHT PANEL: User Input Area */}
                                                                                                                                                                                                                                                                                                          <div className="ratings-panel" style={{ padding: '40px', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
                                                                                                                                                                                                                                                                                                                    {hasSubmitted ? (
                                                                                                                                                                                                                                                                                                                                <SubmissionFeedback />
                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                      <>
                                                                                                                                                                                                                                                                                                                                                                    <h3 style={{ fontSize: '24px', fontWeight: '800', color: 'var(--text-main)', margin: '0 0 8px 0', letterSpacing: '-0.5px' }}>
                                                                                                                                                                                                                                                                                                                                                                                    Rate your experience
                                                                                                                                                                                                                                                                                                                                                                                                  </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                <p style={{ fontSize: '14px', color: 'var(--text-muted)', margin: '0 0 32px 0' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                Tap a star below to let us know how we are doing.
                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <InteractiveStars 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          currentRating={userRating} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onRatingSelect={setUserRating} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          disabled={isSubmitting} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginTop: '16px', color: 'var(--status-error)', fontSize: '13px', fontWeight: '600' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ marginTop: '32px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className={`ayabus-btn ${userRating > 0 ? 'ayabus-btn-primary' : 'ayabus-btn-ghost'}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={handleRatingSubmit}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          disabled={userRating === 0 || isSubmitting}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ width: '100%', justifyContent: 'center', opacity: userRating === 0 ? 0.5 : 1, transition: 'all var(--duration-fast)' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {isSubmitting ? 'Submitting...' : 'Submit Rating'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* --- RESPONSIVE CSS INJECTION --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <style>{`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .ratings-matrix {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        align-items: stretch;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .ratings-panel {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            flex: 1 1 50%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /* Mobile Adjustments */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @media (max-width: 768px) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .ratings-matrix {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          flex-direction: column;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .ratings-panel {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: 32px 24px !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border-right: none !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border-bottom: 1px solid var(--border-subtle);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default RatingsModule;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                