import React, { useState, useEffect, useMemo } from 'react';
import FAQSearch from './components/FAQSearch';
import FAQCategoryTabs from './components/FAQCategoryTabs';
import FAQAccordion from './components/FAQAccordion';
import { fetchFAQs } from './data/faqApi';

const FAQModule = () => {
  const [faqs, setFaqs] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
      const [searchQuery, setSearchQuery] = useState('');
        const [activeCategory, setActiveCategory] = useState('PASSENGER');
          const [openFaqId, setOpenFaqId] = useState(null);

            useEffect(() => {
                let mounted = true;
                    const loadFaqs = async () => {
                          const data = await fetchFAQs();
                                if (mounted) {
                                        setFaqs(data);
                                                setIsLoading(false);
                                                      }
                                                          };
                                                              loadFaqs();
                                                                  return () => { mounted = false; };
                                                                    }, []);

                                                                      // Lightning-fast client-side filtering engine
                                                                        const filteredFaqs = useMemo(() => {
                                                                            return faqs.filter(faq => {
                                                                                  const matchesCategory = faq.category === activeCategory;
                                                                                        const matchesSearch = faq.question.toLowerCase().includes(searchQuery.toLowerCase()) || 
                                                                                                                    faq.answer.toLowerCase().includes(searchQuery.toLowerCase());
                                                                                                                          return matchesCategory && matchesSearch;
                                                                                                                              });
                                                                                                                                }, [faqs, activeCategory, searchQuery]);

                                                                                                                                  const toggleAccordion = (id) => {
                                                                                                                                      setOpenFaqId(prevId => (prevId === id ? null : id));
                                                                                                                                        };

                                                                                                                                          return (
                                                                                                                                              <div className="ayabus-card" style={{ padding: '0', overflow: 'hidden', backgroundColor: 'var(--bg-canvas)' }}>
                                                                                                                                                    <div className="faq-matrix">
                                                                                                                                                            
                                                                                                                                                                    {/* LEFT COLUMN: Context & Controls */}
                                                                                                                                                                            <div className="faq-control-panel" style={{ padding: '48px', borderRight: '1px solid var(--border-subtle)', backgroundColor: 'var(--bg-surface)' }}>
                                                                                                                                                                                      <h2 style={{ fontSize: '32px', fontWeight: '900', color: 'var(--text-main)', margin: '0 0 16px 0', letterSpacing: '-1px' }}>
                                                                                                                                                                                                  We're here to help.
                                                                                                                                                                                                            </h2>
                                                                                                                                                                                                                      <p style={{ fontSize: '15px', color: 'var(--text-muted)', margin: '0 0 32px 0', lineHeight: '1.6' }}>
                                                                                                                                                                                                                                  Find immediate answers to the most common questions from our travelers and partner operators.
                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                      <FAQSearch searchQuery={searchQuery} setSearchQuery={setSearchQuery} />
                                                                                                                                                                                                                                                                <FAQCategoryTabs activeCategory={activeCategory} setActiveCategory={setActiveCategory} />
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                    <div style={{ marginTop: '24px', padding: '24px', backgroundColor: 'var(--brand-subtle)', borderRadius: 'var(--radius-md)' }}>
                                                                                                                                                                                                                                                                                                <h4 style={{ margin: '0 0 8px 0', fontSize: '14px', fontWeight: '800', color: 'var(--brand-primary)' }}>
                                                                                                                                                                                                                                                                                                              Need more help?
                                                                                                                                                                                                                                                                                                                          </h4>
                                                                                                                                                                                                                                                                                                                                      <p style={{ margin: '0 0 16px 0', fontSize: '13px', color: 'var(--text-muted)' }}>
                                                                                                                                                                                                                                                                                                                                                    Our support team is available 24/7 to assist you.
                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                            <button className="ayabus-btn ayabus-btn-primary" style={{ width: '100%', justifyContent: 'center', fontSize: '12px' }}>
                                                                                                                                                                                                                                                                                                                                                                                          Contact Support
                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                {/* RIGHT COLUMN: The Accordion List */}
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="faq-list-panel" style={{ padding: '48px 48px 48px 32px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {isLoading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', opacity: 0.5 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {[1, 2, 3, 4].map(i => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={i} style={{ height: '40px', backgroundColor: 'var(--border-subtle)', borderRadius: 'var(--radius-sm)', animation: 'pulse 1.5s infinite' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : filteredFaqs.length > 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', flexDirection: 'column' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {filteredFaqs.map(faq => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <FAQAccordion 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={faq.id} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              faq={faq} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                isOpen={openFaqId === faq.id} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onToggle={() => toggleAccordion(faq.id)} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ textAlign: 'center', padding: '64px 0', color: 'var(--text-muted)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round" style={{ marginBottom: '16px', opacity: 0.5 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 style={{ fontSize: '16px', fontWeight: '700', color: 'var(--text-main)', margin: '0 0 8px 0' }}>No answers found</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ fontSize: '14px', margin: 0 }}>We couldn't find anything matching "{searchQuery}".</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* --- RESPONSIVE CSS INJECTION --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <style>{`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .faq-matrix {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      align-items: stretch;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .faq-control-panel {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          flex: 0 0 40%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .faq-list-panel {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flex: 1 1 60%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* Mobile Adjustments */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @media (max-width: 992px) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .faq-matrix {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  flex-direction: column;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .faq-control-panel {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  flex: 1 1 auto;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: 32px 24px !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border-right: none !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border-bottom: 1px solid var(--border-subtle);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .faq-list-panel {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: 32px 24px !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              `}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default FAQModule;