import React, { useState, useEffect } from 'react';
import FooterBrand from './components/FooterBrand';
import FooterLinksColumn from './components/FooterLinksColumn';
import FooterBottom from './components/FooterBottom';
import { fetchFooterConfig } from './data/footerApi';

const BigFooterModule = () => {
  const [config, setConfig] = useState(null);
    const [isLoading, setIsLoading] = useState(true);

      useEffect(() => {
          let mounted = true;
              const loadConfig = async () => {
                    const liveData = await fetchFooterConfig();
                          if (mounted) {
                                  setConfig(liveData);
                                          setIsLoading(false);
                                                }
                                                    };
                                                        loadConfig();
                                                            return () => { mounted = false; };
                                                              }, []);

                                                                return (
                                                                    <footer style={{ 
                                                                          backgroundColor: 'var(--bg-canvas)', // Grounded base color
                                                                                borderTop: '1px solid var(--border-subtle)',
                                                                                      padding: '80px 0 32px 0',
                                                                                            width: '100%',
                                                                                                  position: 'relative',
                                                                                                        zIndex: 'var(--z-base)'
                                                                                                            }}>
                                                                                                                  <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '0 32px' }}>
                                                                                                                          
                                                                                                                                  {/* BIG FOOTER MATRIX (Grid Layout) */}
                                                                                                                                          <div className="footer-matrix">
                                                                                                                                                    
                                                                                                                                                              {/* Column 1: Heavy Branding */}
                                                                                                                                                                        <div className="footer-brand-col">
                                                                                                                                                                                     {isLoading ? (
                                                                                                                                                                                                    <div style={{ width: '200px', height: '150px', backgroundColor: 'var(--border-subtle)', animation: 'pulse 1.5s infinite', borderRadius: 'var(--radius-md)' }} />
                                                                                                                                                                                                                 ) : (
                                                                                                                                                                                                                                <FooterBrand config={config} />
                                                                                                                                                                                                                                             )}
                                                                                                                                                                                                                                                       </div>

                                                                                                                                                                                                                                                                 {/* Columns 2, 3, 4: Dynamic Links from Control Centre */}
                                                                                                                                                                                                                                                                           <div className="footer-links-grid">
                                                                                                                                                                                                                                                                                       {isLoading ? (
                                                                                                                                                                                                                                                                                                      // Loading skeletons for link columns
                                                                                                                                                                                                                                                                                                                     [1, 2, 3].map(i => (
                                                                                                                                                                                                                                                                                                                                      <div key={i} style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                                                                                                                                                                                                                                                                                                                                                         <div style={{ width: '80px', height: '16px', backgroundColor: 'var(--border-subtle)', animation: 'pulse 1.5s infinite' }} />
                                                                                                                                                                                                                                                                                                                                                                            <div style={{ width: '120px', height: '14px', backgroundColor: 'var(--border-subtle)', animation: 'pulse 1.5s infinite' }} />
                                                                                                                                                                                                                                                                                                                                                                                               <div style={{ width: '100px', height: '14px', backgroundColor: 'var(--border-subtle)', animation: 'pulse 1.5s infinite' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                               ))
                                                                                                                                                                                                                                                                                                                                                                                                                                           ) : config?.columns?.map((col, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                         <FooterLinksColumn key={index} title={col.title} links={col.links} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {/* BOTTOM ROW */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <FooterBottom />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   {/* --- RESPONSIVE CSS INJECTION --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <style>{`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 .footer-matrix {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     justify-content: space-between;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               gap: 64px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 .footer-brand-col {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           flex: 0 0 320px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           .footer-links-grid {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     flex: 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               display: grid;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   gap: 40px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   /* Tablet Adjustments */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           @media (max-width: 992px) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     .footer-matrix {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 flex-direction: column;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             gap: 48px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 .footer-brand-col {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             flex: 1 1 auto;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         max-width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   /* Mobile Adjustments */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           @media (max-width: 576px) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     .footer-links-grid {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 grid-template-columns: 1fr 1fr; /* 2 columns on small screens */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             gap: 32px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     `}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           export default BigFooterModule;