import React, { useState, useRef, useEffect } from 'react';
import SearchSuggestions from './SearchSuggestions';

const AccommodationSearch = ({ searchParams, updateParams, onSearch }) => {
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
    const wrapperRef = useRef(null);

      // Click-Outside Listener: Closes the dropdown if the user clicks anywhere else on the screen
        useEffect(() => {
            const handleClickOutside = (event) => {
                  if (wrapperRef.current && !wrapperRef.current.contains(event.target)) {
                          setIsDropdownOpen(false);
                                }
                                    };
                                        document.addEventListener('mousedown', handleClickOutside);
                                            return () => document.removeEventListener('mousedown', handleClickOutside);
                                              }, []);

                                                const handleCitySelect = (selectedCity) => {
                                                    updateParams({ ...searchParams, city: selectedCity });
                                                        setIsDropdownOpen(false); // Close dropdown upon selection
                                                          };

                                                            return (
                                                                <div className="ayabus-card" style={{ display: 'flex', flexWrap: 'wrap', gap: '16px', alignItems: 'flex-end', marginBottom: '24px', overflow: 'visible' }}>
                                                                      
                                                                            {/* DESTINATION FIELD W/ AUTO-COMPLETE */}
                                                                                  <div ref={wrapperRef} style={{ flex: '1 1 250px', position: 'relative' }}>
                                                                                          <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-muted)', marginBottom: '8px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                                                                                                    Destination City
                                                                                                            </label>
                                                                                                                    <input 
                                                                                                                              type="text" 
                                                                                                                                        className="ayabus-input" 
                                                                                                                                                  value={searchParams.city} 
                                                                                                                                                            onChange={(e) => {
                                                                                                                                                                        updateParams({ ...searchParams, city: e.target.value });
                                                                                                                                                                                    setIsDropdownOpen(true);
                                                                                                                                                                                              }}
                                                                                                                                                                                                        onFocus={() => setIsDropdownOpen(true)}
                                                                                                                                                                                                                  placeholder="Where are you heading?"
                                                                                                                                                                                                                            autoComplete="off" // Disables browser's native ugly autocomplete
                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                    {/* The Live Wire connection to the Suggestions engine */}
                                                                                                                                                                                                                                                            {isDropdownOpen && (
                                                                                                                                                                                                                                                                      <SearchSuggestions 
                                                                                                                                                                                                                                                                                  query={searchParams.city} 
                                                                                                                                                                                                                                                                                              onSelect={handleCitySelect} 
                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                            {/* DATES & ACTION */}
                                                                                                                                                                                                                                                                                                                                  <div style={{ flex: '1 1 140px' }}>
                                                                                                                                                                                                                                                                                                                                          <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-muted)', marginBottom: '8px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                                                                                                                                                                                                                                                                                                                                                    Check In
                                                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                                                    <input 
                                                                                                                                                                                                                                                                                                                                                                              type="date" 
                                                                                                                                                                                                                                                                                                                                                                                        className="ayabus-input" 
                                                                                                                                                                                                                                                                                                                                                                                                  value={searchParams.checkIn} 
                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => updateParams({ ...searchParams, checkIn: e.target.value })}
                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ flex: '1 1 140px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-muted)', marginBottom: '8px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Check Out
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="date" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="ayabus-input" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={searchParams.checkOut} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => updateParams({ ...searchParams, checkOut: e.target.value })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="ayabus-btn ayabus-btn-primary" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setIsDropdownOpen(false); // Force close dropdown on search click
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onSearch();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ flex: '0 0 auto' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Search Verified Stays
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default AccommodationSearch;