import React, { useState, useEffect, useCallback } from 'react';

const PriceSlider = ({ min, max, step, initialValue, onChange, currency = "UGX" }) => {
  const [minVal, setMinVal] = useState(initialValue[0]);
    const [maxVal, setMaxVal] = useState(initialValue[1]);

      // Convert values to percentage for the dynamic track fill
        const getPercent = useCallback(
            (value) => Math.round(((value - min) / (max - min)) * 100),
                [min, max]
                  );

                    // Trigger the parent's onChange debounced or on mouse up
                      useEffect(() => {
                          const handler = setTimeout(() => {
                                if (onChange) onChange([minVal, maxVal]);
                                    }, 300); // 300ms debounce to prevent excessive re-renders during slide
                                        return () => clearTimeout(handler);
                                          }, [minVal, maxVal, onChange]);

                                            const handleMinChange = (event) => {
                                                const value = Math.min(Number(event.target.value), maxVal - step);
                                                    setMinVal(value);
                                                      };

                                                        const handleMaxChange = (event) => {
                                                            const value = Math.max(Number(event.target.value), minVal + step);
                                                                setMaxVal(value);
                                                                  };

                                                                    return (
                                                                        <div style={{ width: '100%', padding: '10px 0' }}>
                                                                              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '16px' }}>
                                                                                      <div style={{ display: 'flex', flexDirection: 'column' }}>
                                                                                                <span style={{ fontSize: '12px', color: 'var(--text-muted)', fontWeight: '600' }}>Min Price</span>
                                                                                                          <span style={{ fontSize: '14px', color: 'var(--text-main)', fontWeight: '800' }}>{currency} {minVal.toLocaleString()}</span>
                                                                                                                  </div>
                                                                                                                          <div style={{ display: 'flex', flexDirection: 'column', textAlign: 'right' }}>
                                                                                                                                    <span style={{ fontSize: '12px', color: 'var(--text-muted)', fontWeight: '600' }}>Max Price</span>
                                                                                                                                              <span style={{ fontSize: '14px', color: 'var(--text-main)', fontWeight: '800' }}>{currency} {maxVal.toLocaleString()}</span>
                                                                                                                                                      </div>
                                                                                                                                                            </div>

                                                                                                                                                                  <div style={{ position: 'relative', height: '6px', width: '100%' }}>
                                                                                                                                                                          {/* The Track Background */}
                                                                                                                                                                                  <div style={{
                                                                                                                                                                                            position: 'absolute',
                                                                                                                                                                                                      width: '100%',
                                                                                                                                                                                                                height: '100%',
                                                                                                                                                                                                                          backgroundColor: 'var(--border-subtle)',
                                                                                                                                                                                                                                    borderRadius: 'var(--radius-full)',
                                                                                                                                                                                                                                              zIndex: 1
                                                                                                                                                                                                                                                      }} />

                                                                                                                                                                                                                                                              {/* The Active Range Fill */}
                                                                                                                                                                                                                                                                      <div style={{
                                                                                                                                                                                                                                                                                position: 'absolute',
                                                                                                                                                                                                                                                                                          height: '100%',
                                                                                                                                                                                                                                                                                                    backgroundColor: 'var(--brand-primary)',
                                                                                                                                                                                                                                                                                                              borderRadius: 'var(--radius-full)',
                                                                                                                                                                                                                                                                                                                        zIndex: 2,
                                                                                                                                                                                                                                                                                                                                  left: `${getPercent(minVal)}%`,
                                                                                                                                                                                                                                                                                                                                            width: `${getPercent(maxVal) - getPercent(minVal)}%`
                                                                                                                                                                                                                                                                                                                                                    }} />

                                                                                                                                                                                                                                                                                                                                                            {/* Min Input */}
                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                              type="range"
                                                                                                                                                                                                                                                                                                                                                                                        min={min}
                                                                                                                                                                                                                                                                                                                                                                                                  max={max}
                                                                                                                                                                                                                                                                                                                                                                                                            step={step}
                                                                                                                                                                                                                                                                                                                                                                                                                      value={minVal}
                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={handleMinChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                          className="ayabus-range-thumb"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ zIndex: minVal > max - 100 ? 5 : 3 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Max Input */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="range"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                min={min}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          max={max}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    step={step}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={maxVal}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={handleMaxChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="ayabus-range-thumb"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ zIndex: 4 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Internal CSS for the hidden inputs to turn them into purely interactive thumbs */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <style>{`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .ayabus-range-thumb {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        position: absolute;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  pointer-events: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -webkit-appearance: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                height: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          outline: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    top: 3px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              margin: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .ayabus-range-thumb::-webkit-slider-thumb {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pointer-events: all;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -webkit-appearance: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: 20px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      height: 20px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background-color: var(--bg-surface);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: 2px solid var(--brand-primary);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border-radius: 50%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              box-shadow: 0 2px 6px rgba(0,0,0,0.2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: pointer;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  transform: translateY(-50%);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transition: transform var(--duration-fast);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .ayabus-range-thumb::-webkit-slider-thumb:hover {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transform: translateY(-50%) scale(1.1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .ayabus-range-thumb::-moz-range-thumb {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pointer-events: all;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: 20px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    height: 20px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background-color: var(--bg-surface);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: 2px solid var(--brand-primary);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border-radius: 50%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cursor: pointer;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transform: translateY(-50%);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default PriceSlider;