import React, { useState, useEffect } from 'react';
import StatCard from './components/StatCard';
import StatSkeleton from './components/StatSkeleton';
import { fetchMetrics } from './data/metricsApi';

const NumbersModule = () => {
  const [metrics, setMetrics] = useState(null);
    const [isLoading, setIsLoading] = useState(true);

      useEffect(() => {
          let mounted = true;
              const loadData = async () => {
                    const data = await fetchMetrics();
                          if (mounted) {
                                  setMetrics(data);
                                          setIsLoading(false);
                                                }
                                                    };
                                                        loadData();
                                                            return () => { mounted = false; };
                                                              }, []);

                                                                // SVG Icons built inline for zero-latency loading
                                                                  const ICONS = {
                                                                      partners: <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>,
                                                                          routes: <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>,
                                                                              tickets: <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="4" width="20" height="16" rx="2"></rect><path d="M7 4v16"></path><path d="M17 4v16"></path><rect x="11" y="8" width="2" height="8"></rect></svg>,
                                                                                  passengers: <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"></path><line x1="7" y1="7" x2="7.01" y2="7"></line></svg>
                                                                                    };

                                                                                      return (
                                                                                          <section style={{ 
                                                                                                width: '100%', 
                                                                                                      backgroundColor: 'var(--bg-canvas)', // Respects the dark/light mode canvas background
                                                                                                            borderTop: '1px solid var(--border-subtle)',
                                                                                                                  borderBottom: '1px solid var(--border-subtle)',
                                                                                                                        padding: '48px 0',
                                                                                                                              overflow: 'hidden'
                                                                                                                                  }}>
                                                                                                                                        <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '0 24px' }}>
                                                                                                                                                
                                                                                                                                                        {/* Ribbon Content Matrix */}
                                                                                                                                                                <div className="numbers-ribbon ayabus-hide-scrollbar">
                                                                                                                                                                          {isLoading ? (
                                                                                                                                                                                      <>
                                                                                                                                                                                                    <StatSkeleton />
                                                                                                                                                                                                                  <StatSkeleton />
                                                                                                                                                                                                                                <StatSkeleton />
                                                                                                                                                                                                                                              <StatSkeleton />
                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                <>
                                                                                                                                                                                                                                                                                              <StatCard label="Bus Partners" value={metrics.partners} icon={ICONS.partners} />
                                                                                                                                                                                                                                                                                                            <StatCard label="Active Routes" value={metrics.routes} icon={ICONS.routes} />
                                                                                                                                                                                                                                                                                                                          <StatCard label="Tickets Sold" value={metrics.tickets} icon={ICONS.tickets} suffix="+" />
                                                                                                                                                                                                                                                                                                                                        <StatCard label="Happy Travelers" value={metrics.passengers} icon={ICONS.passengers} suffix="+" />
                                                                                                                                                                                                                                                                                                                                                    </>
                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                  {/* --- RESPONSIVE CSS INJECTION --- */}
                                                                                                                                                                                                                                                                                                                                                                                        <style>{`
                                                                                                                                                                                                                                                                                                                                                                                                .numbers-ribbon {
                                                                                                                                                                                                                                                                                                                                                                                                          display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                    justify-content: space-between;
                                                                                                                                                                                                                                                                                                                                                                                                                              align-items: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* Mobile Breakpoint: Transforms into a touch-friendly horizontal scroll strip */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                @media (max-width: 768px) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .numbers-ribbon {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      justify-content: flex-start;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  overflow-x: auto;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              scroll-snap-type: x mandatory;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding-bottom: 16px; /* Room for scrollbar if forced */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gap: 24px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          /* Subtle fade indicators on mobile to show scrollability */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .numbers-ribbon::after {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                content: '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            flex: 0 0 24px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default NumbersModule;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          